## Haiku Generic Build Makefile - kernel driver ##
NAME = ectest
TYPE = DRIVER

SRCS = ectest.c

RDEFS =
RSRCS =
LIBS =
LIBPATHS =
SYSTEM_INCLUDE_PATHS =
LOCAL_INCLUDE_PATHS =
OPTIMIZE := FULL
LOCALES =
DEFINES =
WARNINGS = ALL
SYMBOLS =
DEBUGGER =
COMPILER_FLAGS =
LINKER_FLAGS =
DRIVER_PATH =

include /boot/system/develop/etc/makefile-engine
